In [187]:
import numpy as np
import random
a = np.arange(12, 24)
c1 =  a.reshape(3, 4)
c2 = a.reshape(4, 3)
c3 = a.reshape(6, 2)
c4 = a.reshape(2, 6)
c5 = a.reshape(12, 1)

In [52]:
d1 = a.reshape(-1,2)
d2 = a[0:6].reshape(-1,2)
d3 = a[0:2].reshape(-1,2)
d4 = a.reshape(2,-1)
d5 = a[3:5].reshape(2,-1)

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
* Нет, так как одномерным может считаться массив с 1 строкой, насколько я понимаю. 

In [80]:
norm = np.random.normal(0, 1, 12).reshape(3, 4)
new_norm = norm.reshape(12)
new_norm.size == norm.size

True

In [116]:
rev = np.array([i for i in reversed(range(1,22,2))])
rev_2 = np.array([i for i in reversed(range(2,22,2))]).reshape(1,10)
rev_2.shape == rev.shape
# разница в форме - у первого массива показатель строк вообще отсутствует. 
# Хотя по сути это один и тот же вектор
# Кроме того, первый массив длинее второго

False

In [153]:
a = np.ones(shape = [2, 2])
b = np.ones(shape = [3, 2])
c = np.concatenate((a, b), axis = 0)
c.size

10

In [168]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
np.linalg.det(B)
# матрица B является вырожденной, а значит для неё нельзя вычислить обратную матрицу

0.0

In [244]:
random.seed(42)
c = np.random.uniform(0,16,16)
C = c.reshape(4,4)
D = (C*10) + B
D_inv = np.linalg.inv(D)
print(np.linalg.det(D), '\n', D_inv)

-260899772.5493293 
 [[ 0.00660226 -0.00981102 -0.0069139   0.01085037]
 [ 0.01887663 -0.00796324 -0.00102273  0.0013831 ]
 [-0.00058049  0.00658652 -0.00417003  0.00122085]
 [-0.01177274  0.00341783  0.00761899 -0.00456527]]


In [246]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
ind = np.where(D_inv == 0)
ind_2 = np.where(D_inv == 1)

In [249]:
D_inv[ind] = C[ind]
E = D_inv
E[ind_2] = D[ind_2]
E

array([[  6.11234088,   8.17195684,   6.67857605,  67.53724968],
       [ 33.17845877,   5.40184274,  15.08655526, 173.71246912],
       [  8.30064995, 198.48303342,   5.81807364, 367.48513324],
       [ 15.39915672, 162.28516733, 291.55976094,   4.81405296]])